name: Docker Image CI

on:
  push:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
    
    - run: docker build ./client --file Dockerfile --tag iamivke/multi-client
    - run: docker build ./server --file Dockerfile --tag iamivke/multi-server
    - run: docker build ./nginx --file Dockerfile --tag iamivke/multi-nginx
    - run: docker build ./worker --file Dockerfile --tag iamivke/multi-worker

    - run: docker push iamivke/multi-client
    - run: docker push iamivke/multi-nginx
    - run: docker push iamivke/multi-server
    - run: docker push iamivke/multi-worker
