name: Docker Image CI

on:
  push:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
    
    - run: docker build . --file client/Dockerfile --tag iamivke/multi-client
    - run: docker build . --file server/Dockerfile --tag iamivke/multi-server
    - run: docker build . --file nginx/Dockerfile --tag iamivke/multi-nginx
    - run: docker build . --file worker/Dockerfile --tag iamivke/multi-worker

    - run: docker push iamivke/multi-client
    - run: docker push iamivke/multi-nginx
    - run: docker push iamivke/multi-server
    - run: docker push iamivke/multi-worker
